"""
CynthAI_v2 Bot Policies — rule-based opponents for self-play mixing.

FullOffensePolicy:
  Picks the move that maximises estimated damage:
    damage = basePower * STAB (1.5) * type_effectiveness(move_type, opp_types)
  Falls back to random legal action when no move does damage.

RandomPolicy is still in training/rollout.py (shared with rollout).
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import torch
import torch.nn.functional as F

from env.state_encoder import MOVE_INDEX, TYPE_INDEX


# ── Type effectiveness chart (Gen 9) ───────────────────────────────────────────
# Order: __unk__, normal, fire, water, electric, grass, ice, fighting, poison,
#        ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy
_EFF: list[list[float]] = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0, 1, 1, 0.5, 1],
    [1, 1, 0.5, 0.5, 1, 2, 2, 1, 1, 1, 1, 1, 2, 0.5, 1, 0.5, 1, 2, 1],
    [1, 1, 2, 0.5, 1, 0.5, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0.5, 1, 1, 1],
    [1, 1, 1, 2, 0.5, 0.5, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0.5, 1, 1, 1],
    [1, 1, 0.5, 2, 1, 0.5, 1, 1, 0.5, 2, 0.5, 1, 0.5, 2, 1, 0.5, 1, 0.5, 1],
    [1, 1, 0.5, 0.5, 1, 2, 0.5, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 0.5, 1],
    [1, 2, 1, 1, 1, 1, 2, 1, 0.5, 1, 0.5, 0.5, 0.5, 2, 0, 1, 2, 2, 0.5],
    [1, 1, 1, 1, 1, 2, 1, 1, 0.5, 0.5, 1, 1, 1, 0.5, 0, 1, 1, 0, 2],
    [1, 1, 2, 1, 2, 0.5, 1, 1, 2, 1, 0, 1, 0.5, 2, 1, 1, 1, 2, 1],
    [1, 1, 1, 1, 0.5, 2, 1, 2, 1, 1, 1, 1, 2, 0.5, 1, 1, 1, 0.5, 1],
    [1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0.5, 1, 1, 1, 1, 0, 0.5, 1],
    [1, 1, 0.5, 1, 1, 2, 1, 0.5, 0.5, 1, 0.5, 2, 1, 1, 0.5, 1, 2, 0.5, 0.5],
    [1, 1, 2, 1, 1, 1, 2, 0.5, 1, 0.5, 2, 1, 2, 1, 1, 1, 1, 0.5, 1],
    [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 0.5, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0.5, 0],
    [1, 1, 1, 1, 1, 1, 1, 0.5, 1, 1, 1, 2, 1, 1, 2, 1, 0.5, 1, 0.5],
    [1, 1, 0.5, 0.5, 0.5, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0.5, 2],
    [1, 1, 0.5, 1, 1, 1, 1, 2, 0.5, 1, 1, 1, 1, 1, 1, 2, 2, 0.5, 1],
]

N_TYPES = len(_EFF)  # 19


def _type_effectiveness(move_type_idx: int, def_type_idx: int) -> float:
    """Single-type effectiveness: returns 0, 0.5, 1, or 2."""
    if move_type_idx >= N_TYPES or def_type_idx >= N_TYPES:
        return 1.0
    return _EFF[move_type_idx][def_type_idx]


def _multi_effectiveness(move_type_idx: int, def_types: list[int]) -> float:
    """Combined effectiveness against a dual-type defender (multiplied)."""
    eff = 1.0
    for t in def_types:
        eff *= _type_effectiveness(move_type_idx, t)
    return eff


# ── Helpers ────────────────────────────────────────────────────────────────────

def _get_side_active(state: dict, side_idx: int) -> dict:
    """Return the active Pokemon dict for a side."""
    side = state["sides"][side_idx]
    active_set = {i for i in side["active"] if i is not None}
    if not active_set:
        return {}
    active_pos = next(iter(active_set))
    return side["pokemon"][active_pos]


def _get_types(poke_dict: dict) -> list[int]:
    """Return type indices for a Pokemon (1 or 2 types)."""
    types = poke_dict.get("types", [])
    result = []
    for t in types:
        idx = TYPE_INDEX.get(t.lower(), 0)
        if idx != 0:  # skip __unk__
            result.append(idx)
    # Tera type override in damage calculation
    tera = poke_dict.get("tera_type")
    if tera:
        tidx = TYPE_INDEX.get(tera.lower(), 0)
        if tidx != 0:
            result = [tidx]  # tera changes to single type for STAB/effectiveness
    if not result:
        result = [0]  # fallback: unknown
    return result


# ── FullOffensePolicy ──────────────────────────────────────────────────────────

class FullOffensePolicyOutput:
    """Matches shape of CynthAIAgent output for collect_rollout."""
    def __init__(self, value, log_probs):
        self.value = value
        self.log_probs = log_probs


class FullOffensePolicy:
    """
    Rule-based bot that picks the move with the highest estimated damage.

    Estimates damage as: basePower * STAB * type_effectiveness
    Falls back to random legal action when no move deals damage.

    Call signature matches CynthAIAgent for use in collect_rollout,
    but also supports act_from_states() for richer state access.

    Requires data/move_stats.json (generated by scripts/gen_move_stats.py).
    """

    def __init__(self):
        data_dir = Path(__file__).parent.parent / "data"

        # Load move stats
        with open(data_dir / "move_stats.json") as f:
            self._move_stats: dict[str, dict] = json.load(f)

        # Build reverse index: MOVE_INDEX idx -> PS move ID
        with open(data_dir / "dicts" / "move_index.json") as f:
            mi = json.load(f)["index"]
        self._idx_to_id: dict[int, str] = {v: k for k, v in mi.items()}

    # ── Primary entry point: uses full state dicts ──────────────────────────

    def act(self, states: list[dict], side_idx: int, action_masks: torch.Tensor) -> torch.Tensor:
        """
        Select actions for N environments using damage estimation.

        Args:
            states: [N] battle state dicts from PyBattle.get_state()
            side_idx: 0 or 1, which side this bot controls
            action_masks: [N, 13] bool tensor, True = illegal

        Returns:
            [N] tensor of selected action indices
        """
        B = len(states)
        device = action_masks.device
        actions = torch.zeros(B, dtype=torch.long, device=device)

        for i in range(B):
            mask = action_masks[i]
            legal = torch.nonzero(~mask).squeeze(-1)  # indices of legal actions
            if len(legal) == 0:
                actions[i] = 0
                continue

            active = _get_side_active(states[i], side_idx)
            if not active or active.get("fainted"):
                # Must switch: pick random legal switch (slots 8-12)
                switches = legal[(legal >= 8) & (legal <= 12)]
                if len(switches) > 0:
                    actions[i] = switches[random.randint(0, len(switches) - 1)]
                else:
                    actions[i] = legal[random.randint(0, len(legal) - 1)]
                continue

            move_slots = legal[(legal >= 0) & (legal <= 3)]
            # For non-damaging moves or when no move is legal, fallback to switch
            if len(move_slots) == 0:
                switches = legal[(legal >= 8) & (legal <= 12)]
                if len(switches) > 0:
                    actions[i] = switches[random.randint(0, len(switches) - 1)]
                else:
                    actions[i] = legal[random.randint(0, len(legal) - 1)]
                continue

            attacker_types = _get_types(active)
            opp_active = _get_side_active(states[i], 1 - side_idx)
            defender_types = _get_types(opp_active) if opp_active else [0]

            # Score each legal move slot
            best_score = -1.0
            best_slot = move_slots[0].item()
            for slot in move_slots:
                score = self._score_move(slot, states[i], side_idx, attacker_types, defender_types)
                if score > best_score:
                    best_score = score
                    best_slot = slot.item()

            actions[i] = best_slot

        return actions

    def _score_move(self, slot: int, state: dict, side_idx: int,
                    attacker_types: list[int], defender_types: list[int]) -> float:
        """Estimate damage for one move slot. Returns 0 for status moves."""
        side = state["sides"][side_idx]
        active_set = {i for i in side["active"] if i is not None}
        if not active_set:
            return 0.0
        active_pos = next(iter(active_set))
        active = side["pokemon"][active_pos]
        moves = active.get("moves", [])[:4]

        if slot >= len(moves):
            return 0.0

        move_id_raw = moves[slot].get("id", "")
        if not move_id_raw:
            return 0.0

        stats = self._move_stats.get(move_id_raw)
        if stats is None:
            return 0.0

        bp = stats.get("bp", 0)
        cat = stats.get("cat", "Status")
        if cat == "Status" or bp == 0:
            return 0.0

        move_type_str = stats.get("type", "Normal")
        move_type_idx = TYPE_INDEX.get(move_type_str.lower(), 1)

        # STAB: 1.5 if move type matches any attacker type
        stab = 1.5 if move_type_idx in attacker_types else 1.0

        # Type effectiveness against defender
        eff = _multi_effectiveness(move_type_idx, defender_types)
        if eff == 0:
            return 0.0  # immune, skip

        return bp * stab * eff

    # ── Compatibility interface (agent-like call, less accurate) ────────────

    def __call__(
        self,
        poke_batch, field_tensor,
        move_idx, pp_ratio, move_disabled,
        mechanic_id, mechanic_type_idx,
        action_mask,
    ) -> FullOffensePolicyOutput:
        """
        Minimal agent-compatible call (falls back to random).
        Full damage estimation requires act() with state dicts.
        """
        B = action_mask.shape[0]
        dev = action_mask.device
        logits = torch.zeros(B, 13, device=dev)
        logits = logits.masked_fill(action_mask, -1e9)
        return FullOffensePolicyOutput(
            value=torch.zeros(B, 1, device=dev),
            log_probs=F.log_softmax(logits, dim=-1),
        )

    def eval(self):
        return self

    def to(self, device):
        return self

    def parameters(self):
        return []

    def state_dict(self):
        return {}